name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Triggers on push to the main branch
  pull_request:
    branches:
      - main  # Triggers on pull requests targeting the main branch

jobs:
  # Job for linting HTML, CSS, and JavaScript files
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up HTML, CSS, and JS Linting
        run: |
          sudo apt-get install -y htmlhint
          sudo apt-get install -y csslint
          sudo apt-get install -y jshint

      - name: Lint HTML files
        run: htmlhint ./**/*.html

      - name: Lint CSS files
        run: csslint ./**/*.css

      - name: Lint JavaScript files
        run: jshint ./**/*.js

  # Job for deployment to GitHub Pages
  deploy:
    runs-on: ubuntu-latest
    needs: lint  # Ensure deployment only happens after successful linting
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build the Application (Optional)
        run: echo "No build required for this static project"  # You can skip this if no build step is required

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # All files in the root directory will be deployed to GitHub Pages
