name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Triggered on push to the main branch
  pull_request:
    branches:
      - main  # Triggered on pull requests targeting the main branch

jobs:
  # Job for linting HTML, CSS, and JavaScript files
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js (for linting)
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Set Node.js version to 16.x (adjust as needed)

      - name: Install Linter Dependencies
        run: |
          npm install -g htmlhint csslint jshint  # Install linters globally via npm

      - name: Lint HTML files
        run: htmlhint ./**/*.html  # Lint all HTML files

      - name: Lint CSS files
        run: csslint ./*.css  # Adjust the path to your CSS files

      - name: Lint JavaScript files
        run: jshint ./**/*.js  # Lint all JS files

  # Job for deployment to GitHub Pages
  deploy:
    runs-on: ubuntu-latest
    needs: lint  # Ensure deployment happens after linting is successful
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build the Application (Optional)
        run: echo "No build required for this static project"  # No build step for static project

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # All files in the root directory will be deployed to GitHub Pages
